Endre fra NAV til Nav på minside
navikt/familie-ef-minside pull request #211
Opened 2024-11-11 11:35 UTC by charliemidtlyng

### Hvorfor er denne endringen nødvendig? ✨

2024-11-11 11:37 UTC, gunnsteingarmo requested changes
Hva skjer med package-lock?

2024-11-13 08:05 UTC, charliemidtlyng commented
> Hva skjer med package-lock?

Kjørte `npm install` 

Ser ut som vi har hatt samme endringer i `familie-ef-soknad` også.  Selv om jeg ruller tilbake så forsvinner de når jeg kjører `npm install`

2024-11-13 08:07 UTC, gunnsteingarmo approved these changes

2024-11-13 08:21 UTC, ViktorGSolberg approved these changes
Så lenge appen kjører i preprod med de endringene er det vel greit?

2024-11-13 08:30 UTC, merged